package cn.offway.zeus.enums;

/**
 * 快递编码
 * @author wn
 *
 */
public enum ExpressCodeEnum {
	
	_yunda("yunda", "韵达快递"),
	_huitongkuaidi("huitongkuaidi", "百世快递"),
	_youzhengguonei("youzhengguonei", "邮政快递包裹"),
	_shentong("shentong", "申通快递"),
	_yuantong("yuantong", "圆通速递"),
	_zhongtong("zhongtong", "中通快递"),
	_shunfeng("shunfeng", "顺丰速运"),
	_jd("jd", "京东物流"),
	_ems("ems", "EMS"),
	_youzhengguoji("youzhengguoji", "国际包裹"),
	_tiantian("tiantian", "天天快递"),
	_emsguoji("emsguoji", "EMS-国际件"),
	_debangwuliu("debangwuliu", "德邦"),
	_emsinten("emsinten", "EMS-国际件-英文"),
	_emsen("emsen", "EMS-英文"),
	_dhlen("dhlen", "DHL-全球件"),
	_youshuwuliu("youshuwuliu", "优速物流"),
	_baishiwuliu("baishiwuliu", "百世快运"),
	_zhaijisong("zhaijisong", "宅急送"),
	_pjbest("pjbest", "品骏快递"),
	_disifang("disifang", "递四方"),
	_dhl("dhl", "DHL-中国件"),
	_auspost("auspost", "澳大利亚(Australia Post)"),
	_usps("usps", "USPS"),
	_fedex("fedex", "FedEx-国际件"),
	_kuayue("kuayue", "跨越速运"),
	_debangkuaidi("debangkuaidi", "德邦快递"),
	_ewe("ewe", "EWE全球快递"),
	_japanposten("japanposten", "日本（Japan Post）"),
	_auexpress("auexpress", "澳邮中国快运"),
	_annengwuliu("annengwuliu", "安能快运"),
	_flyway("flyway", "程光快递"),
	_zhongtongkuaiyun("zhongtongkuaiyun", "中通快运"),
	_yundakuaiyun("yundakuaiyun", "韵达快运"),
	_yzguonei("yzguonei", "邮政国内"),
	_suer("suer", "速尔快递"),
	_wherexpess("wherexpess", "威盛快递"),
	_quanfengkuaidi("quanfengkuaidi", "全峰快递"),
	_guangdongyouzhengwuliu("guangdongyouzhengwuliu", "广东邮政"),
	_upsen("upsen", "UPS-全球件"),
	_ups("ups", "UPS"),
	_ubonex("ubonex", "优邦速运"),
	_aramex("aramex", "Aramex"),
	_fedexus("fedexus", "FedEx-美国件"),
	_ndwl("ndwl", "南方传媒物流"),
	_hkpost("hkpost", "中国香港(HongKong Post)"),
	_rrs("rrs", "日日顺物流"),
	_guotongkuaidi("guotongkuaidi", "国通快递"),
	_yuxinwuliu("yuxinwuliu", "宇鑫物流"),
	_emsbg("emsbg", "EMS包裹"),
	_meiquick("meiquick", "美快国际物流"),
	_coe("coe", "COE"),
	_qexpress("qexpress", "易达通快递"),
	_zhuanyunsifang("zhuanyunsifang", "转运四方"),
	_ausexpress("ausexpress", "澳世速递"),
	_youzhengbk("youzhengbk", "邮政标准快递"),
	_kuaijiesudi("kuaijiesudi", "快捷速递"),
	_sxexpress("sxexpress", "三象速递"),
	_wanxiangwuliu("wanxiangwuliu", "万象物流"),
	_tnt("tnt", "TNT"),
	_aae("aae", "AAE-中国件"),
	_longbanwuliu("longbanwuliu", "龙邦速递"),
	_dhlde("dhlde", "DHL-德国件（DHL Deutschland）"),
	_ftd("ftd", "富腾达国际货运"),
	_shpost("shpost", "同城快寄"),
	_lianhaowuliu("lianhaowuliu", "联昊通"),
	_zhongtongphone("zhongtongphone", "中通（带电话）"),
	_yimidida("yimidida", "壹米滴答"),
	_suning("suning", "苏宁物流"),
	_lntjs("lntjs", "特急送"),
	_quanyikuaidi("quanyikuaidi", "全一快递"),
	_jxfex("jxfex", "集先锋快递"),
	_transrush("transrush", "TransRush"),
	_yuantongkuaiyun("yuantongkuaiyun", "圆通快运"),
	_unitedex("unitedex", "联合速运"),
	_astexpress("astexpress", "安世通快递"),
	_annto("annto", "安得物流"),
	_lianbangkuaidi("lianbangkuaidi", "联邦快递"),
	_banma("banma", "斑马物流"),
	_zhaijibian("zhaijibian", "宅急便"),
	_stosolution("stosolution", "申通国际"),
	_yousutongda("yousutongda", "优速通达"),
	_superb("superb", "Superb Grace"),
	_xinbangwuliu("xinbangwuliu", "新邦物流"),
	_xlobo("xlobo", "Xlobo贝海国际"),
	_xinfengwuliu("xinfengwuliu", "信丰物流"),
	_ueq("ueq", "UEQ快递"),
	_sxhongmajia("sxhongmajia", "红马甲物流"),
	_nsf("nsf", "新顺丰（NSF）"),
	_zhongsukuaidi("zhongsukuaidi", "中速快递"),
	_gxwl("gxwl", "光线速递"),
	_euasia("euasia", "欧亚专线"),
	_jiajiwuliu("jiajiwuliu", "佳吉快运"),
	_ontrac("ontrac", "OnTrac"),
	_subida("subida", "速必达"),
	_gdkd("gdkd", "港快速递"),
	_parcelforce("parcelforce", "英国大包、EMS（Parcel Force）"),
	_sdto("sdto", "速达通"),
	_postnlcn("postnlcn", "荷兰邮政-中文(PostNL international registered mail)"),
	_ytchengnuoda("ytchengnuoda", "承诺达"),
	_jinguangsudikuaijian("jinguangsudikuaijian", "京广速递"),
	_ocs("ocs", "OCS"),
	_hengluwuliu("hengluwuliu", "恒路物流"),
	_zhongtiewuliu("zhongtiewuliu", "中铁快运"),
	_crazyexpress("crazyexpress", "疯狂快递"),
	_valueway("valueway", "美通"),
	_zhongtongguoji("zhongtongguoji", "中通国际"),
	_exfresh("exfresh", "安鲜达"),
	_yundaexus("yundaexus", "美国云达"),
	_chnexp("chnexp", "中翼国际物流"),
	_yuntongkuaidi("yuntongkuaidi", "运通中港"),
	_esinotrans("esinotrans", "中外运"),
	_tnten("tnten", "TNT-全球件"),
	_cnair("cnair", "CNAIR"),
	_pochta("pochta", "俄罗斯邮政(Russian Post)"),
	_postserv("postserv", "台湾（中华邮政）"),
	_changjiang("changjiang", "长江国际速递"),
	_ecmscn("ecmscn", "易客满"),
	_dpex("dpex", "DPEX"),
	_stoe56("stoe56", "申通快运"),
	_shenghuiwuliu("shenghuiwuliu", "盛辉物流"),
	_yangbaoguo("yangbaoguo", "洋包裹"),
	_fedexcn("fedexcn", "Fedex-国际件-中文"),
	_zhonghuan("zhonghuan", "中环快递"),
	_zlxdjwl("zlxdjwl", "中粮鲜到家物流"),
	_dpduk("dpduk", "DPD UK"),
	_eusacn("eusacn", "优莎速运"),
	_cnpex("cnpex", "CNPEX中邮快递"),
	_xunsuexpress("xunsuexpress", "迅速快递"),
	_dpexen("dpexen", "Toll"),
	_zhongyouwuliu("zhongyouwuliu", "中邮物流"),
	_bsht("bsht", "百事亨通"),
	_jialidatong("jialidatong", "嘉里大通"),
	_chengguangkuaidi("chengguangkuaidi", "程光快递"),
	_edtexpress("edtexpress", "e直运"),
	_bulgarian("bulgarian", "保加利亚（Bulgarian Posts）"),
	_ztky("ztky", "中铁物流"),
	_jiayunmeiwuliu("jiayunmeiwuliu", "加运美"),
	_arkexpress("arkexpress", "方舟速递"),
	_sunjex("sunjex", "新杰物流"),
	_polarexpress("polarexpress", "极地快递"),
	_dsukuaidi("dsukuaidi", "D速快递"),
	_meiguokuaidi("meiguokuaidi", "美国快递"),
	_meixi("meixi", "美西快递"),
	_synship("synship", "SYNSHIP快递"),
	_anxl("anxl", "安迅物流"),
	_huanqiu("huanqiu", "环球速运"),
	_uluckex("uluckex", "优联吉运"),
	_youyou("youyou", "优优速递"),
	_royalmail("royalmail", "英国小包（Royal Mail）"),
	_singpost("singpost", "新加坡小包(Singapore Post)"),
	_bpost("bpost", "比利时（Bpost）"),
	_canpost("canpost", "加拿大(Canada Post)"),
	_yafengsudi("yafengsudi", "亚风速递"),
	_chukou1("chukou1", "出口易"),
	_rufengda("rufengda", "如风达"),
	_zteexpress("zteexpress", "ZTE中兴物流"),
	_hyytes("hyytes", "恒宇运通"),
	_japanpost("japanpost", "日本郵便"),
	_koreapost("koreapost", "韩国（Korea Post）"),
	_macao("macao", "中国澳门(Macau Post)"),
	_blueskyexpress("blueskyexpress", "蓝天快递"),
	_postnl("postnl", "荷兰邮政(PostNL international registered mail)"),
	_citylink("citylink", "City-Link"),
	_bpostinter("bpostinter", "比利时国际(Bpost international)"),
	_swisspostcn("swisspostcn", "瑞士邮政"),
	_jieanda("jieanda", "捷安达"),
	_hrex("hrex", "锦程快递"),
	_hd("hd", "宏递快运"),
	_datianwuliu("datianwuliu", "大田物流"),
	_tntuk("tntuk", "TNT UK"),
	_nanjingshengbang("nanjingshengbang", "晟邦物流"),
	_epanex("epanex", "泛捷国际速递"),
	_swisspost("swisspost", "瑞士(Swiss Post)"),
	_hkposten("hkposten", "中国香港(HongKong Post)英文"),
	_cnexps("cnexps", "CNE"),
	_dpd("dpd", "DPD"),
	_deutschepost("deutschepost", "德国(Deutsche Post)"),
	_iyoungspeed("iyoungspeed", "驿扬国际速运"),
	_littlebearbear("littlebearbear", "小熊物流"),
	_shunfengen("shunfengen", "顺丰-美国件"),
	_guexp("guexp", "全联速运"),
	_httx56("httx56", "汇通天下物流"),
	_la911("la911", "鼎润物流"),
	_newsway("newsway", "家家通快递"),
	_csuivi("csuivi", "法国(La Poste)"),
	_shunfenghk("shunfenghk", "顺丰-繁体"),
	_ane66("ane66", "安能快递"),
	_royalmailcn("royalmailcn", "英国邮政小包"),
	_tntau("tntau", "TNT Australia"),
	_yuantongguoji("yuantongguoji", "圆通国际"),
	_colissimo("colissimo", "法国小包（colissimo）"),
	_ucs("ucs", "合众速递(UCS）"),
	_westwing("westwing", "西翼物流"),
	_zhongchuan("zhongchuan", "众川国际"),
	_ruidianyouzheng("ruidianyouzheng", "瑞典（Sweden Post）"),
	_fastway("fastway", "Fastway Ireland"),
	_lantiankuaidi("lantiankuaidi", "蓝天快递"),
	_shengfengwuliu("shengfengwuliu", "盛丰物流"),
	_uspscn("uspscn", "USPSCN"),
	_hermes("hermes", "Hermes"),
	_qinyuan("qinyuan", "秦远物流"),
	_shangcheng("shangcheng", "尚橙物流"),
	_suteng("suteng", "广东速腾物流"),
	_sendtochina("sendtochina", "速递中国"),
	_yuanchengwuliu("yuanchengwuliu", "远成物流"),
	_sxjdfreight("sxjdfreight", "顺心捷达"),
	_yuananda("yuananda", "源安达"),
	_correosdees("correosdees", "西班牙(Correos de Espa?a)"),
	_pcaexpress("pcaexpress", "PCA Express"),
	_szuem("szuem", "联运通物流"),
	_adapost("adapost", "安达速递"),
	_jiacheng("jiacheng", "佳成快递 "),
	_nederlandpost("nederlandpost", "荷兰速递(Nederland Post)"),
	_postnlpacle("postnlpacle", "荷兰包裹(PostNL International Parcels)"),
	_luben("luben", "陆本速递 LUBEN EXPRESS"),
	_belgiumpost("belgiumpost", "比利时(Belgium Post)"),
	_bdatong("bdatong", "八达通"),
	_tstexp("tstexp", "TST速运通"),
	_italiane("italiane", "意大利(Poste Italiane)"),
	_koalaexp("koalaexp", "考拉速递"),
	_tykd("tykd", "天翼快递"),
	_pingandatengfei("pingandatengfei", "平安达腾飞"),
	_kingfreight("kingfreight", "货运皇"),
	_jinan("jinan", "金岸物流"),
	_zyzoom("zyzoom", "增速跨境 "),
	_auod("auod", "澳德物流"),
	_jiazhoumao("jiazhoumao", "加州猫速递"),
	_ycgky("ycgky", "远成快运"),
	_aotsd("aotsd", "澳天速运"),
	_uszcn("uszcn", "转运中国"),
	_ganzhongnengda("ganzhongnengda", "能达速递"),
	_jiujiuwl("jiujiuwl", "久久物流"),
	_newzealand("newzealand", "新西兰（New Zealand Post）"),
	_cces("cces", "CCES/国通快递"),
	_decnlh("decnlh", "德中快递"),
	_wjkwl("wjkwl", "万家康物流"),
	_aus("aus", "澳世速递"),
	_chronopostfra("chronopostfra", "法国大包、EMS-法文（Chronopost France）"),
	_jiayiwuliu("jiayiwuliu", "佳怡物流"),
	_nebuex("nebuex", "星云速递"),
	_shipgce("shipgce", "飞洋快递"),
	_yingchao("yingchao", "英超物流"),
	_wlwex("wlwex", "星空国际"),
	_yue777("yue777", "玥玛速运"),
	_zengyisudi("zengyisudi", "增益速递"),
	_cnausu("cnausu", "中澳速递"),
	_nuoyaao("nuoyaao", "偌亚奥国际快递"),
	_baitengwuliu("baitengwuliu", "百腾物流"),
	_chinaicip("chinaicip", "卓志速运"),
	_koreapostcn("koreapostcn", "韩国邮政"),
	_bqcwl("bqcwl", "百千诚物流"),
	_jym56("jym56", "加运美速递"),
	_sagawa("sagawa", "佐川急便"),
	_sutongwuliu("sutongwuliu", "速通物流"),
	_fastgo("fastgo", "速派快递(FastGo)"),
	_kjde("kjde", "跨境直邮通"),
	_lijisong("lijisong", "成都立即送"),
	_anxindakuaixi("anxindakuaixi", "安信达"),
	_zhongjiwuliu("zhongjiwuliu", "中技物流"),
	_minghangkuaidi("minghangkuaidi", "民航快递"),
	_yidatong("yidatong", "易达通"),
	_aolau("aolau", "AOL澳通速递"),
	_dhlbenelux("dhlbenelux", "DHL Benelux"),
	_india("india", "印度(India Post)"),
	_newgistics("newgistics", "Newgistics"),
	_hgy56("hgy56", "环国运物流"),
	_freakyquick("freakyquick", "FQ狂派速递"),
	_uhi("uhi", "优海国际速递"),
	_boyol("boyol", "贝业物流"),
	_easyexpress("easyexpress", "EASY EXPRESS"),
	_cllexpress("cllexpress", "澳通华人物流"),
	_kfwnet("kfwnet", "快服务"),
	_asendiausa("asendiausa", "Asendia USA"),
	_jgwl("jgwl", "景光物流"),
	_beebird("beebird", "锋鸟物流"),
	_efs("efs", "EFS Post（平安快递）"),
	_bosind("bosind", "堡昕德速递"),
	_yujiawl("yujiawl", "宇佳物流"),
	_ukrpostcn("ukrpostcn", "乌克兰邮政包裹"),
	_wanjiawuliu("wanjiawuliu", "万家物流"),
	_heimao56("heimao56", "黑猫速运"),
	_stoexpress("stoexpress", "美国申通"),
	_suijiawuliu("suijiawuliu", "穗佳物流"),
	_airpak("airpak", "airpak expresss"),
	_hangrui("hangrui", "上海航瑞货运"),
	_hnht56("hnht56", "鸿泰物流"),
	_malaysiapost("malaysiapost", "马来西亚小包（Malaysia Post(Registered)）"),
	_qichen("qichen", "启辰国际速递"),
	_thailand("thailand", "泰国（Thailand Thai Post）"),
	_baifudongfang("baifudongfang", "百福东方"),
	_jsexpress("jsexpress", "骏绅物流"),
	_amusorder("amusorder", "amazon-国际订单"),
	_beckygo("beckygo", "佰麒快递"),
	_benteng("benteng", "奔腾物流"),
	_comexpress("comexpress", "邦通国际"),
	_aosu("aosu", "澳速物流"),
	_koreapostkr("koreapostkr", "韩国邮政韩文"),
	_wondersyd("wondersyd", "中邮速递"),
	_sccod("sccod", "丰程物流"),
	_signedexpress("signedexpress", "签收快递"),
	_emonitoring("emonitoring", "波兰小包(Poczta Polska)"),
	_hongpinwuliu("hongpinwuliu", "宏品物流"),
	_malaysiaems("malaysiaems", "马来西亚大包、EMS（Malaysia Post(parcel,EMS)）"),
	_postdanmarken("postdanmarken", "丹麦(Post Denmark)"),
	_xdexpress("xdexpress", "迅达速递"),
	_bjemstckj("bjemstckj", "北京EMS"),
	_homecourier("homecourier", "如家国际快递"),
	_jindawuliu("jindawuliu", "金大物流"),
	_shd56("shd56", "商海德物流"),
	_taijin("taijin", "泰进物流"),
	_wuliuky("wuliuky", "五六快运"),
	_bht("bht", "BHT"),
	_doortodoor("doortodoor", "CJ物流"),
	_ytkd("ytkd", "运通中港快递"),
	_ltexp("ltexp", "乐天速递"),
	_trackparcel("trackparcel", "track-parcel"),
	_huanqiuabc("huanqiuabc", "中国香港环球快运"),
	_quanritongkuaidi("quanritongkuaidi", "全日通"),
	_dechuangwuliu("dechuangwuliu", "深圳德创物流"),
	_eta100("eta100", "易达国际速递"),
	_haimibuy("haimibuy", "海米派物流"),
	_tywl99("tywl99", "天翼物流"),
	_anposten("anposten", "爱尔兰(An Post)"),
	_austria("austria", "奥地利(Austrian Post)"),
	_jietekuaidi("jietekuaidi", "捷特快递"),
	_uscbexpress("uscbexpress", "易境达国际物流"),
	_bangsongwuliu("bangsongwuliu", "邦送物流"),
	_chuanxiwuliu("chuanxiwuliu", "传喜物流"),
	_georgianpost("georgianpost", "格鲁吉亚(Georgian Pos）"),
	_zjstky("zjstky", "苏通快运"),
	_auvanda("auvanda", "中联速递"),
	_dekuncn("dekuncn", "德坤物流"),
	_gongsuda("gongsuda", "共速达"),
	_huaqikuaiyun("huaqikuaiyun", "华企快运"),
	_xynyc("xynyc", "新元国际"),
	_yfsuyun("yfsuyun", "驭丰速运"),
	_canpostfr("canpostfr", "加拿大邮政"),
	_chuangyi("chuangyi", "创一快递"),
	_dayangwuliu("dayangwuliu", "大洋物流"),
	_ghtexpress("ghtexpress", "GHT物流"),
	_guoeryue("guoeryue", "天天快物流"),
	_lbex("lbex", "龙邦物流"),
	_shangda("shangda", "上大物流"),
	_shlindao("shlindao", "林道国际快递"),
	_trakpak("trakpak", "TRAKPAK"),
	_wtdchina("wtdchina", "威时沛运货运"),
	_zhongtianwanyun("zhongtianwanyun", "中天万运"),
	_anjiekuaidi("anjiekuaidi", "青岛安捷快递"),
	_gslexpress("gslexpress", "德尚国际速递"),
	_junfengguoji("junfengguoji", "骏丰国际速递"),
	_mingliangwuliu("mingliangwuliu", "明亮物流"),
	_omniva("omniva", "爱沙尼亚(Eesti Post)"),
	_ptt("ptt", "土耳其"),
	_speedpost("speedpost", "新加坡EMS、大包(Singapore Speedpost)"),
	_topspeedex("topspeedex", "中运全速"),
	_ynztsy("ynztsy", "纵通速运"),
	_jingshun("jingshun", "景顺物流"),
	_logistics("logistics", "華信物流WTO"),
	_wotu("wotu", "渥途国际速运"),
	_yuefengwuliu("yuefengwuliu", "越丰物流"),
	_abcglobal("abcglobal", "全球快运"),
	_biaojikuaidi("biaojikuaidi", "彪记快递"),
	_changyuwuliu("changyuwuliu", "长宇物流"),
	_chengjisudi("chengjisudi", "城际速递"),
	_ecallturn("ecallturn", "E跨通"),
	_feibaokuaidi("feibaokuaidi", "飞豹快递"),
	_ftky365("ftky365", "丰通快运"),
	_ht22("ht22", "海淘物流"),
	_longfx("longfx", "龙飞祥快递"),
	_nalexpress("nalexpress", "新亚物流"),
	_santaisudi("santaisudi", "三态速递"),
	_szyouzheng("szyouzheng", "深圳邮政"),
	_vnpost("vnpost", "越南EMS(VNPost Express)"),
	_aplus100("aplus100", "美国汉邦快递"),
	_bee001("bee001", "蜜蜂速递"),
	_ceskaposta("ceskaposta", "捷克（?eská po?ta）"),
	_cuckooexpess("cuckooexpess", "布谷鸟速递"),
	_eltahell("eltahell", "希腊EMS（ELTA Courier）"),
	_feikangda("feikangda", "飞康达"),
	_landmarkglobal("landmarkglobal", "Landmark Global"),
	_ldxpres("ldxpres", "林道国际快递-英文"),
	_nntengda("nntengda", "腾达速递"),
	_quanjitong("quanjitong", "全际通"),
	_quansu("quansu", "全速物流"),
	_shunjiefengda("shunjiefengda", "顺捷丰达"),
	_sinatone("sinatone", "信联通"),
	_yamaxunwuliu("yamaxunwuliu", "亚马逊中国"),
	_zgyzt("zgyzt", "一站通快递"),
	_fecobv("fecobv", "丰客物流"),
	_feiyuanvipshop("feiyuanvipshop", "飞远配送"),
	_hungary("hungary", "匈牙利（Magyar Posta）"),
	_jieborne("jieborne", "捷邦物流"),
	_latvia("latvia", "拉脱维亚(Latvijas Pasts)"),
	_mauritius("mauritius", "毛里求斯(Mauritius Post)"),
	_postelbe("postelbe", "PostElbe"),
	_sundarexpress("sundarexpress", "顺达快递"),
	_xianglongyuntong("xianglongyuntong", "祥龙运通物流"),
	_xtb("xtb", "鑫通宝物流"),
	_yibangwuliu("yibangwuliu", "一邦速递"),
	_yodel("yodel", "YODEL"),
	_yufeng("yufeng", "御风速运"),
	_zhongwaiyun("zhongwaiyun", "中外运速递"),
	_a2u("a2u", "A2U速递"),
	_adlerlogi("adlerlogi", "德国雄鹰速递"),
	_ajexpress("ajexpress", "捷记方舟"),
	_buytong("buytong", "百通物流"),
	_cameroon("cameroon", "喀麦隆(CAMPOST)"),
	_canhold("canhold", "能装能送"),
	_ccd("ccd", "河南次晨达"),
	_chszhonghuanguoji("chszhonghuanguoji", "CHS中环国际快递"),
	_dindon("dindon", "叮咚澳洲转运"),
	_dpdgermany("dpdgermany", "DPD Germany"),
	_dpdpoland("dpdpoland", "DPD Poland"),
	_eshunda("eshunda", "俄顺达"),
	_express7th("express7th", "7号速递"),
	_fanyukuaidi("fanyukuaidi", "凡宇快递"),
	_fedexuk("fedexuk", "FedEx-英国件（FedEx UK)"),
	_gaotieex("gaotieex", "高铁快运"),
	_hzpl("hzpl", "华航快递"),
	_indonesia("indonesia", "印度尼西亚EMS(Pos Indonesia-EMS)"),
	_jiajikuaidi("jiajikuaidi", "佳吉快递"),
	_jixianda("jixianda", "急先达"),
	_kuaiyouda("kuaiyouda", "四川快优达速递"),
	_lqht("lqht", "恒通快递"),
	_nlebv("nlebv", "亚欧专线"),
	_portugalctt("portugalctt", "葡萄牙（Portugal CTT）"),
	_postennorge("postennorge", "挪威（Posten Norge）"),
	_riyuwuliu("riyuwuliu", "日昱物流"),
	_sfift("sfift", "十方通物流"),
	_shiningexpress("shiningexpress", "阳光快递"),
	_southafrican("southafrican", "南非（South African Post Office）"),
	_vangenexpress("vangenexpress", "万庚国际速递"),
	_vctrans("vctrans", "越中国际物流"),
	_ydglobe("ydglobe", "云达通"),
	_yyox("yyox", "邮客全球速递"),
	_1ziton("1ziton", "一智通"),
	_abf("abf", "ABF"),
	_adaexpress("adaexpress", "明大快递"),
	_albania("albania", "阿尔巴尼亚(Posta shqipatre)"),
	_alog("alog", "心怡物流"),
	_anjie88("anjie88", "安捷物流"),
	_auex("auex", "澳货通"),
	_chengji("chengji", "城际快递"),
	_chile("chile", "智利(Correos Chile)"),
	_cloudexpress("cloudexpress", "CE易欧通国际速递"),
	_cncexp("cncexp", "C&C国际速递"),
	_correo("correo", "乌拉圭（Correo Uruguayo）"),
	_dadaoex("dadaoex", "大道物流"),
	_dongjun("dongjun", "成都东骏物流"),
	_emirates("emirates", "阿联酋(Emirates Post)"),
	_farlogistis("farlogistis", "泛远国际物流"),
	_finland("finland", "芬兰(Itella Posti Oy)"),
	_fox("fox", "FOX国际快递"),
	_gls("gls", "GLS"),
	_gsm("gsm", "GSM"),
	_haihongwangsong("haihongwangsong", "海红网送"),
	_hitaoe("hitaoe", "Hi淘易快递"),
	_lejiedi("lejiedi", "乐捷递"),
	_lsexpress("lsexpress", "6LS EXPRESS"),
	_nigerianpost("nigerianpost", "尼日利亚(Nigerian Postal)"),
	_onway("onway", "昂威物流"),
	_qskdyxgs("qskdyxgs", "千顺快递"),
	_saiaodi("saiaodi", "赛澳递"),
	_saiaodimmb("saiaodimmb", "赛澳递for买卖宝"),
	_shangqiao56("shangqiao56", "商桥物流"),
	_spring56("spring56", "春风物流"),
	_stkd("stkd", "顺通快递"),
	_sujievip("sujievip", "郑州速捷"),
	_surpassgo("surpassgo", "天越物流"),
	_turtle("turtle", "海龟国际快递"),
	_uex("uex", "UEX国际物流"),
	_uzbekistan("uzbekistan", "乌兹别克斯坦(Post of Uzbekistan)"),
	_xingyuankuaidi("xingyuankuaidi", "新元快递"),
	_yinjiesudi("yinjiesudi", "银捷速递"),
	_yiouzhou("yiouzhou", "易欧洲国际物流"),
	_yuandun("yuandun", "远盾物流"),
	_yuanhhk("yuanhhk", "远航国际快运"),
	_yunexpress("yunexpress", "德国云快递"),
	_ztjieda("ztjieda", "泰捷达国际物流"),
	_56kuaiyun("56kuaiyun", "五六快运"),
	_adiexpress("adiexpress", "安达易国际速递"),
	_adp("adp", "ADP国际快递"),
	_advancing("advancing", "安达信"),
	_airgtc("airgtc", "航空快递"),
	_anlexpress("anlexpress", "新干线快递"),
	_aplusex("aplusex", "Aplus物流"),
	_bazirim("bazirim", "皮牙子快递"),
	_belize("belize", "伯利兹(Belize Postal)"),
	_brazilposten("brazilposten", "巴西(Brazil Post/Correios)"),
	_byht("byht", "展勤快递"),
	_cambodia("cambodia", "柬埔寨(Cambodia Post)"),
	_cdek("cdek", "CDEK"),
	_chengda("chengda", "成达国际速递"),
	_chengtong("chengtong", "城通物流"),
	_chronopostfren("chronopostfren", "法国大包、EMS-英文(Chronopost France)"),
	_chunfai("chunfai", "中国香港骏辉物流"),
	_chunghwa56("chunghwa56", "中骅物流"),
	_ctoexp("ctoexp", "泰国中通CTO"),
	_didasuyun("didasuyun", "递达速运"),
	_el56("el56", "易联通达"),
	_ethiopia("ethiopia", "埃塞俄比亚(Ethiopian postal)"),
	_euexpress("euexpress", "EU-EXPRESS"),
	_euguoji("euguoji", "易邮国际"),
	_europeanecom("europeanecom", "europeanecom"),
	_fbkd("fbkd", "飞邦快递"),
	_feikuaida("feikuaida", "飞快达"),
	_gda("gda", "安的快递"),
	_gdrz58("gdrz58", "容智快运"),
	_goldjet("goldjet", "高捷快运"),
	_gts("gts", "GTS快递"),
	_hangyu("hangyu", "航宇快递"),
	_haoshengwuliu("haoshengwuliu", "昊盛物流"),
	_hlyex("hlyex", "好来运"),
	_hmus("hmus", "华美快递"),
	_hre("hre", "高铁速递"),
	_htongexpress("htongexpress", "华通快运"),
	_huandonglg("huandonglg", "环东物流"),
	_huiqiangkuaidi("huiqiangkuaidi", "汇强快递"),
	_iceland("iceland", "冰岛(Iceland Post)"),
	_idada("idada", "大达物流"),
	_inposdom("inposdom", "多米尼加（INPOSDOM – Instituto Postal Dominicano）"),
	_israelpost("israelpost", "以色列(Israel Post)"),
	_jixiangyouau("jixiangyouau", "吉祥邮（澳洲）"),
	_kangliwuliu("kangliwuliu", "康力物流"),
	_kazpost("kazpost", "哈萨克斯坦(Kazpost)"),
	_kcs("kcs", "KCS"),
	_kejie("kejie", "科捷物流"),
	_lao("lao", "老挝(Lao Express) "),
	_lbbk("lbbk", "立白宝凯物流"),
	_lianbangkuaidien("lianbangkuaidien", "联邦快递-英文"),
	_lutong("lutong", "鲁通快运"),
	_luxembourg("luxembourg", "卢森堡(Luxembourg Post)"),
	_lwe("lwe", "LWE"),
	_maxeedexpress("maxeedexpress", "澳洲迈速快递"),
	_mchy("mchy", "木春货运"),
	_mexico("mexico", "墨西哥（Correos de Mexico）"),
	_minbangsudi("minbangsudi", "民邦速递"),
	_mongolpost("mongolpost", "蒙古国(Mongol Post) "),
	_nzzto("nzzto", "新西兰中通"),
	_oman("oman", "阿曼(Oman Post)"),
	_pakistan("pakistan", "巴基斯坦(Pakistan Post)"),
	_peisihuoyunkuaidi("peisihuoyunkuaidi", "配思货运"),
	_phlpost("phlpost", "菲律宾（Philippine Postal）"),
	_posta("posta", "坦桑尼亚（Tanzania Posts Corporation）"),
	_qdants("qdants", "ANTS EXPRESS"),
	_quanchenkuaidi("quanchenkuaidi", "全晨快递"),
	_quanchuan56("quanchuan56", "全川物流"),
	_quansutong("quansutong", "全速通"),
	_republic("republic", "叙利亚(Syrian Post)"),
	_rokin("rokin", "荣庆物流"),
	_romanian("romanian", "罗马尼亚（Posta Romanian）"),
	_safexpress("safexpress", "Safexpress"),
	_serbia("serbia", "塞尔维亚(PE Post of Serbia)"),
	_sfau("sfau", "澳丰速递"),
	_shenganwuliu("shenganwuliu", "圣安物流"),
	_shunjieda("shunjieda", "顺捷达"),
	_sinoairinex("sinoairinex", "中外运空运"),
	_siodemka("siodemka", "Siodemka"),
	_speedoex("speedoex", "申必达"),
	_sunspeedy("sunspeedy", "新速航"),
	_sut56("sut56", "速通物流"),
	_tcat("tcat", "黑猫宅急便"),
	_thaizto("thaizto", "泰国中通ZTO"),
	_tollpriority("tollpriority", "Toll Priority(Toll Online)"),
	_tongdaxing("tongdaxing", "通达兴物流"),
	_tonghetianxia("tonghetianxia", "通和天下"),
	_tzky("tzky", "铁中快运"),
	_ukraine("ukraine", "乌克兰小包、大包(UkrPoshta)"),
	_ukrpost("ukrpost", "乌克兰小包、大包(UkrPost)"),
	_vipexpress("vipexpress", "鹰运国际速递"),
	_whgjkd("whgjkd", "香港伟豪国际物流"),
	_winit("winit", "万邑通"),
	_wykjt("wykjt", "51跨境通"),
	_xianfeng("xianfeng", "先锋快递"),
	_xyd666("xyd666", "鑫远东速运"),
	_yatfai("yatfai", "一辉物流"),
	_yitongda("yitongda", "易通达"),
	_yizhengdasuyun("yizhengdasuyun", "一正达速运"),
	_yongchangwuliu("yongchangwuliu", "永昌物流"),
	_youjia("youjia", "友家速递"),
	_ytky168("ytky168", "运通快运"),
	_yuanzhijiecheng("yuanzhijiecheng", "元智捷诚"),
	_yundx("yundx", "运东西"),
	_yuntong("yuntong", "运通速运"),
	_zf365("zf365", "珠峰速运"),
	_zhonghuanus("zhonghuanus", "中环转运"),
	_zsky123("zsky123", "准实快运"),
	_adodoxm("adodoxm", "澳多多国际速递"),
	_afghan("afghan", "阿富汗(Afghan Post)"),
	_afl("afl", "AFL"),
	_agopost("agopost", "全程快递"),
	_ahdf("ahdf", "德方物流"),
	_ahkbps("ahkbps", "卡邦配送"),
	_aliexpress("aliexpress", "无忧物流"),
	_amazoncnorder("amazoncnorder", "亚马逊中国订单"),
	_amcnorder("amcnorder", "amazon-国内订单"),
	_aruba("aruba", "阿鲁巴[荷兰]（Post Aruba）"),
	_auvexpress("auvexpress", "AUV国际快递"),
	_axexpress("axexpress", "澳新物流"),
	_azerbaijan("azerbaijan", "阿塞拜疆EMS(EMS AzerExpressPost)"),
	_bahrain("bahrain", "巴林(Bahrain Post)"),
	_bangladesh("bangladesh", "孟加拉国(EMS)"),
	_baotongkd("baotongkd", "宝通快递"),
	_baoxianda("baoxianda", "报通快递"),
	_barbados("barbados", "巴巴多斯(Barbados Post)"),
	_bcwelt("bcwelt", "BCWELT"),
	_belpost("belpost", "白俄罗斯(Belpochta)"),
	_benniao("benniao", "笨鸟国际"),
	_bgky100("bgky100", "邦工快运"),
	_bjqywl("bjqywl", "青云物流"),
	_bjxsrd("bjxsrd", "鑫锐达"),
	_bluedart("bluedart", "BlueDart"),
	_bmlchina("bmlchina", "标杆物流"),
	_bohei("bohei", "波黑(JP BH Posta)"),
	_bolivia("bolivia", "玻利维亚"),
	_borderguru("borderguru", "BorderGuru"),
	_botspost("botspost", "博茨瓦纳"),
	_bphchina("bphchina", "速方(Sufast)"),
	_brunei("brunei", "文莱(Brunei Postal)"),
	_caledonia("caledonia", "新喀里多尼亚[法国](New Caledonia)"),
	_cangspeed("cangspeed", "仓鼠快递"),
	_canpar("canpar", "Canpar"),
	_cargolux("cargolux", "卢森堡航空"),
	_cbo56("cbo56", "钏博物流"),
	_cex("cex", "城铁速递"),
	_changwooair("changwooair", "昌宇国际"),
	_chinasqk("chinasqk", "SQK国际速递"),
	_chinatzx("chinatzx", "同舟行物流"),
	_chllog("chllog", "嘉荣物流"),
	_chronopostport("chronopostport", "Chronopost Portugal"),
	_cjkoreaexpress("cjkoreaexpress", "大韩通运"),
	_ckeex("ckeex", "城晓国际快递"),
	_clsp("clsp", "CL日中速运"),
	_cnup("cnup", "CNUP 中联邮"),
	_cnws("cnws", "中国翼"),
	_colombia("colombia", "哥伦比亚(4-72 La Red Postal de Colombia)"),
	_correios("correios", "莫桑比克（Correios de Moçambique）"),
	_correoargentino("correoargentino", "阿根廷(Correo Argentina)"),
	_correos("correos", "哥斯达黎加(Correos de Costa Rica)"),
	_cosco("cosco", "中远e环球"),
	_cpsair("cpsair", "华中快递"),
	_cqxingcheng("cqxingcheng", "重庆星程快递"),
	_csxss("csxss", "新时速物流"),
	_cypruspost("cypruspost", "塞浦路斯(Cyprus Post)"),
	_czwlyn("czwlyn", "云南诚中物流"),
	_dasu("dasu", "达速物流"),
	_dcs("dcs", "DCS"),
	_deguo8elog("deguo8elog", "德国八易转运"),
	_deltec("deltec", "Deltec Courier"),
	_desworks("desworks", "澳行快递"),
	_dfkuaidi("dfkuaidi", "东风快递"),
	_dfpost("dfpost", "达方物流"),
	_dhlecommerce("dhlecommerce", "dhl小包"),
	_dhlhk("dhlhk", "DHL HK"),
	_dhlnetherlands("dhlnetherlands", "DHL-荷兰（DHL Netherlands）"),
	_dhlpoland("dhlpoland", "DHL-波兰（DHL Poland）"),
	_di5pll("di5pll", "递五方云仓"),
	_diantongkuaidi("diantongkuaidi", "店通快递"),
	_dianyi("dianyi", "云南滇驿物流"),
	_dingdong("dingdong", "叮咚快递"),
	_directlink("directlink", "Direct Link"),
	_disifangau("disifangau", "递四方澳洲"),
	_disifangus("disifangus", "递四方美国"),
	_djy56("djy56", "天翔东捷运"),
	_donghanwl("donghanwl", "东瀚物流"),
	_donghong("donghong", "东红物流"),
	_dtdcindia("dtdcindia", "DTDC India"),
	_ealceair("ealceair", "东方航空物流"),
	_ecfirstclass("ecfirstclass", "EC-Firstclass"),
	_ecmsglobal("ecmsglobal", "ECMS Express"),
	_ecotransite("ecotransite", "东西E全运"),
	_ecuador("ecuador", "厄瓜多尔(Correos del Ecuador)"),
	_edaeuexpress("edaeuexpress", "易达快运"),
	_edlogistics("edlogistics", "益递物流"),
	_edragon("edragon", "龙象国际物流"),
	_egypt("egypt", "埃及（Egypt Post）"),
	_elta("elta", "希腊包裹（ELTA Hellenic Post）"),
	_emms("emms", "澳州顺风快递"),
	_emsluqu("emsluqu", "高考通知书"),
	_emssouthafrica("emssouthafrica", "南非EMS"),
	_emsukraine("emsukraine", "乌克兰EMS(EMS Ukraine)"),
	_emsukrainecn("emsukrainecn", "乌克兰EMS-中文(EMS Ukraine)"),
	_england("england", "英国(大包,EMS)"),
	_epspost("epspost", "联众国际"),
	_estafeta("estafeta", "Estafeta"),
	_estes("estes", "Estes"),
	_eucnrail("eucnrail", "中欧国际物流"),
	_eucpost("eucpost", "德国 EUC POST"),
	_europe8("europe8", "败欧洲"),
	_excocotree("excocotree", "可可树美中速运"),
	_expressplus("expressplus", "澳洲新干线快递"),
	_ezhuanyuan("ezhuanyuan", "易转运"),
	_fandaguoji("fandaguoji", "颿达国际快递-英文"),
	_fardarww("fardarww", "颿达国际快递"),
	_fastgoexpress("fastgoexpress", "速派快递"),
	_fastontime("fastontime", "加拿大联通快运"),
	_fedexukcn("fedexukcn", "FedEx-英国件"),
	_fedroad("fedroad", "FedRoad 联邦转运"),
	_feihukuaidi("feihukuaidi", "飞狐快递"),
	_fenghuangkuaidi("fenghuangkuaidi", "凤凰快递"),
	_fiji("fiji", "斐济(Fiji Post)"),
	_flowerkd("flowerkd", "花瓣转运"),
	_flysman("flysman", "飞力士物流"),
	_fsexp("fsexp", "全速快递"),
	_ftlexpress("ftlexpress", "法翔速运"),
	_fyex("fyex", "飞云快递系统"),
	_gansuandi("gansuandi", "甘肃安的快递"),
	_gaticn("gaticn", "Gati-中文"),
	_gatien("gatien", "Gati-英文"),
	_gatikwe("gatikwe", "Gati-KWE"),
	_gdct56("gdct56", "广东诚通物流"),
	_gdxp("gdxp", "新鹏快递"),
	_ge2d("ge2d", "GE2D跨境物流"),
	_ghl("ghl", "环创物流"),
	_gibraltar("gibraltar", "直布罗陀[英国]( Royal Gibraltar Post)"),
	_gjwl("gjwl", "冠捷物流 "),
	_globaltracktrace("globaltracktrace", "globaltracktrace"),
	_gml("gml", "英脉物流"),
	_gotoubi("gotoubi", "UBI Australia"),
	_greenland("greenland", "格陵兰[丹麦]（TELE Greenland A/S）"),
	_gscq365("gscq365", "哥士传奇速递"),
	_gslhkd("gslhkd", "联合快递"),
	_gswtkd("gswtkd", "万通快递"),
	_gtgogo("gtgogo", "GT国际快运"),
	_gtongsudi("gtongsudi", "广通速递"),
	_guangdongtonglu("guangdongtonglu", "广东通路"),
	_guanting("guanting", "冠庭国际物流"),
	_guosong("guosong", "国送快运"),
	_gvpexpress("gvpexpress", "宏观国际快递"),
	_gzxingcheng("gzxingcheng", "贵州星程快递"),
	_haihongmmb("haihongmmb", "海红for买卖宝"),
	_haimengsudi("haimengsudi", "海盟速递"),
	_haiwaihuanqiu("haiwaihuanqiu", "海外环球"),
	_haixingqiao("haixingqiao", "海星桥快递"),
	_handboy("handboy", "汉邦国际速递"),
	_haoyoukuai("haoyoukuai", "好又快物流"),
	_happylink("happylink", "开心快递"),
	_haypost("haypost", "亚美尼亚(Haypost-Armenian Postal)"),
	_hengrui56("hengrui56", "恒瑞物流"),
	_hexinexpress("hexinexpress", "合心速递"),
	_hhair56("hhair56", "华瀚快递"),
	_highsince("highsince", "Highsince"),
	_higo("higo", "黑狗物流"),
	_hipito("hipito", "海派通"),
	_hjs("hjs", "猴急送"),
	_hkems("hkems", "云邮跨境快递"),
	_hlkytj("hlkytj", "互联快运"),
	_hltop("hltop", "海联快递"),
	_hnfy("hnfy", "飞鹰物流"),
	_hnqst("hnqst", "河南全速通"),
	_hnssd56("hnssd56", "顺时达物流"),
	_homexpress("homexpress", "居家通"),
	_hongjie("hongjie", "宏捷国际物流"),
	_hongxun("hongxun", "鸿讯物流"),
	_hqtd("hqtd", "环球通达 "),
	_hrbzykd("hrbzykd", "卓烨快递"),
	_hrvatska("hrvatska", "克罗地亚（Hrvatska Posta）"),
	_hsgtsd("hsgtsd", "海硕高铁速递"),
	_htwd("htwd", "华通务达物流"),
	_huada("huada", "华达快运"),
	_huilian("huilian", "辉联物流"),
	_humpline("humpline", "驼峰国际"),
	_huoban("huoban", "兰州伙伴物流"),
	_hutongwuliu("hutongwuliu", "户通物流"),
	_hyeship("hyeship", "鸿远物流"),
	_hyk("hyk", "上海昊宏国际货物"),
	_ibenben("ibenben", "途鲜物流"),
	_ibuy8("ibuy8", "爱拜物流"),
	_iexpress("iexpress", "iExpress"),
	_ilogen("ilogen", "logen路坚"),
	_ilyang("ilyang", "ILYANG"),
	_interlink("interlink", "Interlink Express"),
	_iparcel("iparcel", "UPS i-parcel"),
	_iran("iran", "伊朗（Iran Post）"),
	_ireland("ireland", "爱尔兰(An Post)"),
	_italysad("italysad", "Italy SDA"),
	_jamaicapost("jamaicapost", "牙买加（Jamaica Post）"),
	_jcex("jcex", "jcex"),
	_jcsuda("jcsuda", "嘉诚速达"),
	_jdexpressusa("jdexpressusa", "骏达快递"),
	_jdiex("jdiex", "JDIEX"),
	_jdpplus("jdpplus", "急递"),
	_jerseypost("jerseypost", "泽西岛"),
	_jiajiatong56("jiajiatong56", "佳家通货运"),
	_jiguang("jiguang", "极光转运"),
	_jinchengwuliu("jinchengwuliu", "锦程物流"),
	_jintongkd("jintongkd", "劲通快递"),
	_jinyuekuaidi("jinyuekuaidi", "晋越快递"),
	_jiugong("jiugong", "九宫物流"),
	_jiuyicn("jiuyicn", "久易快递"),
	_jjx888("jjx888", "佳捷翔物流"),
	_jordan("jordan", "约旦(Jordan Post)"),
	_juwu("juwu", "聚物物流"),
	_kaolaexpress("kaolaexpress", "考拉国际速递"),
	_kenya("kenya", "肯尼亚(POSTA KENYA)"),
	_kerrytj("kerrytj", "嘉里大荣物流"),
	_khzto("khzto", "柬埔寨中通"),
	_koali("koali", "番薯国际货运"),
	_krtao("krtao", "淘韩国际快递"),
	_ksudi("ksudi", "快速递"),
	_kuai8("kuai8", "快8速运"),
	_kuaidawuliu("kuaidawuliu", "快达物流"),
	_kuaitao("kuaitao", "快淘快递"),
	_kxda("kxda", "凯信达"),
	_kyrgyzpost("kyrgyzpost", "吉尔吉斯斯坦(Kyrgyz Post)"),
	_kyue("kyue", "跨跃国际"),
	_lanbiaokuaidi("lanbiaokuaidi", "蓝镖快递"),
	_lanhukuaidi("lanhukuaidi", "蓝弧快递"),
	_laposte("laposte", "塞内加尔"),
	_lasership("lasership", "LaserShip"),
	_lasy56("lasy56", "林安物流"),
	_ledii("ledii", "乐递供应链"),
	_leopard("leopard", "云豹国际货运"),
	_lesotho("lesotho", "莱索托(Lesotho Post)"),
	_letseml("letseml", "美联快递"),
	_lfexpress("lfexpress", "龙枫国际快递"),
	_lianyun("lianyun", "联运快递"),
	_libanpost("libanpost", "黎巴嫩(Liban Post)"),
	_lishi("lishi", "丽狮物流"),
	_lithuania("lithuania", "立陶宛（Lietuvos pa?tas）"),
	_lmfex("lmfex", "良藤国际速递"),
	_longlangkuaidi("longlangkuaidi", "隆浪快递"),
	_longvast("longvast", "长风物流"),
	_ltparcel("ltparcel", "联通快递"),
	_ltx("ltx", "蓝天国际快递"),
	_lundao("lundao", "论道国际物流"),
	_macedonia("macedonia", "马其顿(Macedonian Post)"),
	_macroexpressco("macroexpressco", "ME物流"),
	_mailikuaidi("mailikuaidi", "麦力快递"),
	_mailongdy("mailongdy", "迈隆递运"),
	_maldives("maldives", "马尔代夫(Maldives Post)"),
	_malta("malta", "马耳他（Malta Post）"),
	_mangguo("mangguo", "芒果速递"),
	_mantoo("mantoo", "优能物流"),
	_mapleexpress("mapleexpress", "今枫国际快运"),
	_meibang("meibang", "美邦国际快递"),
	_meidaexpress("meidaexpress", "美达快递"),
	_mexicodenda("mexicodenda", "Mexico Senda Express"),
	_milkyway("milkyway", "银河物流"),
	_minshengkuaidi("minshengkuaidi", "闽盛快递"),
	_mjexp("mjexp", "美龙快递"),
	_moldova("moldova", "摩尔多瓦(Posta Moldovei)"),
	_montenegro("montenegro", "黑山(Posta Crne Gore)"),
	_morocco("morocco", "摩洛哥 ( Morocco Post )"),
	_mosuda("mosuda", "魔速达"),
	_mrw("mrw", "MRW"),
	_multipack("multipack", "Mexico Multipack"),
	_mxe56("mxe56", "中俄速通（淼信）"),
	_myhermes("myhermes", "MyHermes"),
	_namibia("namibia", "纳米比亚(NamPost)"),
	_nedahm("nedahm", "红马速递"),
	_nell("nell", "尼尔快递"),
	_nepalpost("nepalpost", "尼泊尔（Nepal Postal Services）"),
	_nle("nle", "NLE"),
	_nmhuahe("nmhuahe", "华赫物流"),
	_novaposhta("novaposhta", "Nova Poshta"),
	_nuoer("nuoer", "诺尔国际物流"),
	_oborexpress("oborexpress", "OBOR Express"),
	_ocaargen("ocaargen", "OCA Argentina"),
	_opek("opek", "OPEK"),
	_otobv("otobv", "中欧快运"),
	_overseaex("overseaex", "波音速递"),
	_paraguay("paraguay", "巴拉圭(Correo Paraguayo)"),
	_parcelchina("parcelchina", "诚一物流"),
	_parcelforcecn("parcelforcecn", "英国邮政大包EMS"),
	_pdstow("pdstow", "全球速递"),
	_peex("peex", "派尔快递"),
	_peixingwuliu("peixingwuliu", "陪行物流"),
	_pengcheng("pengcheng", "鹏程快递"),
	_pengyuanexpress("pengyuanexpress", "鹏远国际速递"),
	_peru("peru", "秘鲁(SERPOST)"),
	_pfcexpress("pfcexpress", "皇家物流"),
	_pinsuxinda("pinsuxinda", "品速心达快递"),
	_pioneer("pioneer", "先锋国际快递"),
	_polarisexpress("polarisexpress", "北极星快运"),
	_portugalseur("portugalseur", "Portugal Seur"),
	_postenab("postenab", "PostNord(Posten AB)"),
	_postnlchina("postnlchina", "荷兰邮政-中国件"),
	_postpng("postpng", "巴布亚新几内亚(PNG Post)"),
	_purolator("purolator", "Purolator"),
	_pzhjst("pzhjst", "急顺通"),
	_qbexpress("qbexpress", "秦邦快运"),
	_qesd("qesd", "7E速递"),
	_qianli("qianli", "千里速递"),
	_qpost("qpost", "卡塔尔（Qatar Post）"),
	_quantium("quantium", "Quantium"),
	_quantwl("quantwl", "全通快运"),
	_quanxintong("quanxintong", "全信通快递"),
	_qzx56("qzx56", "全之鑫物流"),
	_redexpress("redexpress", "Red Express"),
	_rfsd("rfsd", "瑞丰速递"),
	_rlgaus("rlgaus", "澳洲飞跃物流"),
	_rpx("rpx", "rpx"),
	_rrskx("rrskx", "日日顺快线"),
	_rrthk("rrthk", "日日通国际"),
	_ruexp("ruexp", "捷网俄全通"),
	_ruidaex("ruidaex", "瑞达国际速递"),
	_runhengfeng("runhengfeng", "全时速运"),
	_rwanda("rwanda", "卢旺达(Rwanda i-posita)"),
	_rytsd("rytsd", "日益通速递"),
	_s2c("s2c", "S2C"),
	_samoa("samoa", "萨摩亚(Samoa Post)"),
	_sanshengco("sanshengco", "三盛快递"),
	_saudipost("saudipost", "沙特阿拉伯(Saudi Post)"),
	_scic("scic", "中加国际快递"),
	_scxingcheng("scxingcheng", "四川星程快递"),
	_sczpds("sczpds", "速呈"),
	_sd138("sd138", "泰国138国际物流"),
	_sdsy888("sdsy888", "首达速运"),
	_sdyoupei("sdyoupei", "优配速运"),
	_selektvracht("selektvracht", "Selektvracht"),
	_seur("seur", "International Seur"),
	_sfjhd("sfjhd", "圣飞捷快递"),
	_sfwl("sfwl", "盛丰物流"),
	_shanda56("shanda56", "衫达快运"),
	_shanghaikuaitong("shanghaikuaitong", "上海快通"),
	_shanghaiwujiangmmb("shanghaiwujiangmmb", "上海无疆for买卖宝"),
	_shaoke("shaoke", "捎客物流"),
	_shengtongscm("shengtongscm", "盛通快递"),
	_shenma("shenma", "神马快递"),
	_shipbyace("shipbyace", "王牌快递"),
	_shipsoho("shipsoho", "苏豪快递"),
	_shiyunkuaidi("shiyunkuaidi", "世运快递"),
	_shlexp("shlexp", "SHL畅灵国际物流"),
	_shpostwish("shpostwish", "wish邮"),
	_shunbang("shunbang", "顺邦国际物流"),
	_shunshid("shunshid", "顺士达速运"),
	_sihaiet("sihaiet", "四海快递"),
	_sihiexpress("sihiexpress", "四海捷运"),
	_sinoex("sinoex", "中外运速递-中文"),
	_sixroad("sixroad", "易普递"),
	_skynet("skynet", "skynet"),
	_skynetmalaysia("skynetmalaysia", "SkyNet Malaysia"),
	_skypost("skypost", "荷兰Sky Post"),
	_slovak("slovak", "斯洛伐克(Slovenská Posta)"),
	_slovenia("slovenia", "斯洛文尼亚(Slovenia Post)"),
	_slpost("slpost", "斯里兰卡(Sri Lanka Post)"),
	_sofast56("sofast56", "嗖一下同城快递"),
	_speeda("speeda", "行必达"),
	_staky("staky", "首通快运"),
	_starex("starex", "星速递"),
	_staryvr("staryvr", "星运快递"),
	_sucheng("sucheng", "速呈宅配"),
	_sucmj("sucmj", "特急便物流"),
	_sudapost("sudapost", "苏丹（Sudapost）"),
	_superoz("superoz", "速配欧翼"),
	_supinexpress("supinexpress", "速品快递"),
	_sureline("sureline", "Sureline冠泰"),
	_sycawl("sycawl", "狮爱高铁物流"),
	_szdpex("szdpex", "深圳DPEX"),
	_taimek("taimek", "天美快递"),
	_tanzania("tanzania", "坦桑尼亚(Tanzania Posts)"),
	_taoplus("taoplus", "淘布斯国际物流"),
	_tcixps("tcixps", "TCI XPS"),
	_tcxbthai("tcxbthai", "TCXB国际物流"),
	_tianma("tianma", "天马迅达"),
	_tianxiang("tianxiang", "天翔快递"),
	_tianzong("tianzong", "天纵物流"),
	_timedg("timedg", "万家通快递"),
	_tlky("tlky", "天联快运"),
	_tmg("tmg", "株式会社T.M.G"),
	_tntitaly("tntitaly", "TNT Italy"),
	_tntpostcn("tntpostcn", "TNT Post"),
	_tny("tny", "TNY物流"),
	_toll("toll", "Toll"),
	_topshey("topshey", "顶世国际物流"),
	_tswlcloud("tswlcloud", "天使物流云"),
	_tunisia("tunisia", "突尼斯EMS(Rapid-Poste)"),
	_ubuy("ubuy", "德国优拜物流"),
	_uganda("uganda", "乌干达(Posta Uganda)"),
	_ugoexpress("ugoexpress", "邮鸽速运"),
	_upsfreight("upsfreight", "UPS Freight"),
	_upsmailinno("upsmailinno", "UPS Mail Innovations"),
	_utaoscm("utaoscm", "UTAO优到"),
	_vancl("vancl", "凡客配送（作废）"),
	_vanuatu("vanuatu", "瓦努阿图(Vanuatu Post)"),
	_vietnam("vietnam", "越南小包(Vietnam Posts)"),
	_vps("vps", "维普恩物流"),
	_wanboex("wanboex", "万博快递"),
	_wandougongzhu("wandougongzhu", "豌豆物流"),
	_wanjiatong("wanjiatong", "宁夏万家通"),
	_wdm("wdm", "万达美"),
	_weilaimingtian("weilaimingtian", "未来明天快递"),
	_wenjiesudi("wenjiesudi", "文捷航空"),
	_wlfast("wlfast", "凡仕特物流"),
	_wtdex("wtdex", "WTD海外通"),
	_wto56kj("wto56kj", "温通物流"),
	_wuyuansudi("wuyuansudi", "伍圆速递"),
	_wzhaunyun("wzhaunyun", "微转运"),
	_xaetc("xaetc", "西安胜峰"),
	_xdshipping("xdshipping", "国晶物流"),
	_xianchengliansudi("xianchengliansudi", "西安城联速递"),
	_xiangdawuliu("xiangdawuliu", "湘达物流"),
	_xiangteng("xiangteng", "翔腾物流"),
	_xiaocex("xiaocex", "小C海淘"),
	_xilaikd("xilaikd", "西安喜来快递"),
	_xinning("xinning", "新宁物流"),
	_xintianjie("xintianjie", "信天捷快递"),
	_xipost("xipost", "西邮寄"),
	_xiyoug("xiyoug", "西游寄"),
	_xsrd("xsrd", "鑫世锐达"),
	_yatexpress("yatexpress", "乾坤物流"),
	_ycgglobal("ycgglobal", "YCG物流"),
	_yemen("yemen", "也门(Yemen Post)"),
	_yhtlogistics("yhtlogistics", "宇航通物流"),
	_yidihui("yidihui", "驿递汇速递"),
	_yiex("yiex", "宜送物流"),
	_yifankd("yifankd", "艺凡快递"),
	_yihangmall("yihangmall", "易航物流"),
	_yilingsuyun("yilingsuyun", "亿领速运"),
	_yinsu("yinsu", "音素快运"),
	_yiqiguojiwuliu("yiqiguojiwuliu", "一柒国际物流"),
	_yiqisong("yiqisong", "一起送"),
	_yisong("yisong", "宜送"),
	_yiyou("yiyou", "易邮速运"),
	_ykouan("ykouan", "洋口岸"),
	_yongbangwuliu("yongbangwuliu", "永邦国际物流"),
	_yongwangda("yongwangda", "永旺达快递"),
	_youban("youban", "邮邦国际"),
	_youlai("youlai", "邮来速递"),
	_yourscm("yourscm", "雅澳物流"),
	_ypsd("ypsd", "壹品速递"),
	_yuezhongsh("yuezhongsh", "粤中国际货运代理（上海）有限公司"),
	_yujiawuliu("yujiawuliu", "煜嘉物流"),
	_yunfeng56("yunfeng56", "韵丰物流"),
	_yuntrack("yuntrack", "YUN TRACK"),
	_yw56("yw56", "燕文物流"),
	_ywexpress("ywexpress", "远为快递"),
	_yyexp("yyexp", "西安运逸快递"),
	_yyqc56("yyqc56", "一运全成物流"),
	_yzswuliu("yzswuliu", "亚洲顺物流"),
	_zenzen("zenzen", "三三国际物流"),
	_zhdwl("zhdwl", "众辉达物流"),
	_zhichengtongda("zhichengtongda", "至诚通达快递"),
	_zhitengwuliu("zhitengwuliu", "志腾物流"),
	_zhongruisudi("zhongruisudi", "中睿速递"),
	_zhongxinda("zhongxinda", "忠信达"),
	_zhpex("zhpex", "众派速递"),
	_zhuoshikuaiyun("zhuoshikuaiyun", "卓实快运"),
	_zjgj56("zjgj56", "振捷国际货运"),
	_zqlwl("zqlwl", "青旅物流"),
	_zsda56("zsda56", "转瞬达集运"),
	_zsmhwl("zsmhwl", "明辉物流"),
	_ztong("ztong", "智通物流");

    private String code;

    private String desc;

    private ExpressCodeEnum(String code, String desc) {
        this.code = code;
        this.desc = desc;
    }

    public static ExpressCodeEnum getByCode(String code) {
        for (ExpressCodeEnum enumObj : ExpressCodeEnum.values()) {
            if (enumObj.getCode().equals(code)) {
                return enumObj;
            }
        }
        return null;
    }
    
    public static ExpressCodeEnum getByDesc(String desc) {
        for (ExpressCodeEnum enumObj : ExpressCodeEnum.values()) {
            if (enumObj.getDesc().equals(desc)) {
                return enumObj;
            }
        }
        return null;
    }

    public String getCode() {
        return code;
    }

    public String getDesc() {
        return desc;
    }
}
